version: '3.8'

services:
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - mern-network

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server_image
    ports:
      - "8000:8000"  # Port for the backend
    volumes:
      - ./backend:/app  # Bind mount for live reloading
    # depends_on:
    #   - mongo
    env_file:
      - .env
    networks:
      - mern-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client_image
    ports:
      - "3000:3000"  # Port for the React app
    depends_on:
      - server
    networks:
      - mern-network

# volumes:
#   mongo-data:

networks:
  mern-network:
    driver: bridge
